trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.12'
  appName: 'gsm-fastapi'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(pythonVersion)'
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true
    architecture: 'x64'

- task: ArchiveFiles@2
  displayName: 'Zip Code'
  inputs:
     rootFolderOrFile: '$(Build.SourcesDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/$(appName)_$(Build.BuildId).zip'
     replaceExistingArchive: true
     verbose: true

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: 'AlongX-Azure-Account-Development'
    appType: 'webAppLinux'
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/$(appName)_$(Build.BuildId).zip'